export const templates = {
    professional: {
        name: "text-3xl font-bold text-gray-800 mb-2",
        contact: "text-sm text-gray-600 mb-4",
        sectionTitle: "text-xl font-bold mt-6 mb-3 text-gray-800 border-b border-gray-300 pb-1",
        itemTitle: "text-lg font-semibold text-gray-800",
        itemSubtitle: "text-sm text-gray-600 italic",
        itemDescription: "text-sm text-gray-700 mt-1",
        customSection: "mt-4",
        container: "bg-white p-8 max-w-2xl mx-auto shadow-sm"
    },
    modern: {
        name: "text-4xl font-bold text-blue-700 mb-2",
        contact: "text-sm text-blue-600 mb-6",
        sectionTitle: "text-2xl font-bold mt-8 mb-4 text-blue-700",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-blue-600 font-medium",
        itemDescription: "text-sm text-gray-700 mt-2 leading-relaxed",
        customSection: "mt-6 pl-4 border-l-4 border-blue-200",
        container: "bg-white p-8 max-w-2xl mx-auto"
    },
    creative: {
        name: "text-4xl font-bold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-pink-500",
        contact: "text-sm text-gray-500 mb-6",
        sectionTitle: "text-xl font-bold mt-8 mb-3 text-purple-700 uppercase tracking-wider",
        itemTitle: "text-lg font-bold text-gray-900",
        itemSubtitle: "text-sm text-pink-600 font-medium",
        itemDescription: "text-sm text-gray-700 mt-2 pl-4 border-l-2 border-purple-200",
        customSection: "mt-6 bg-gray-50 p-4 rounded-lg",
        container: "bg-white p-6 max-w-2xl mx-auto border-l-8 border-purple-500"
    },
    nordic: {
        container: "bg-white p-8 max-w-2xl mx-auto border border-gray-100 shadow-sm",
        name: "text-3xl font-light text-gray-800 mb-1 tracking-wide",
        contact: "text-sm text-gray-500 mb-6",
        sectionTitle: "text-lg font-medium text-gray-700 uppercase tracking-widest border-b border-gray-100 pb-2 mb-3",
        itemTitle: "text-base font-normal text-gray-900",
        itemSubtitle: "text-xs text-gray-500 italic",
        itemDescription: "text-sm text-gray-600 mt-1 leading-snug",
        customSection: "mt-4 pl-2 border-l-2 border-gray-200",
        accentColor: "text-gray-800"
    },
    darkTech: {
        container: "bg-gray-900 p-8 max-w-2xl mx-auto text-gray-100",
        name: "text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-emerald-400 text-ellipsis",
        contact: "text-blue-300 text-sm mb-6",
        sectionTitle: "text-xl font-mono text-blue-400 border-b border-blue-800 pb-1 mb-3",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-blue-300 font-mono",
        itemDescription: "text-gray-300 mt-2 text-sm",
        customSection: "mt-6 bg-gray-800 p-3 rounded",
        accentColor: "text-blue-400"
    },
    vintage: {
        container: "bg-amber-50 p-8 max-w-2xl mx-auto border-l-4 border-amber-300",
        name: "text-4xl font-serif text-amber-900 mb-2",
        contact: "text-amber-700 text-sm italic mb-6",
        sectionTitle: "text-xl font-serif text-amber-800 border-b border-amber-200 pb-1 mb-3",
        itemTitle: "text-lg font-serif text-amber-900",
        itemSubtitle: "text-sm text-amber-600",
        itemDescription: "text-amber-800 mt-1 text-sm leading-relaxed",
        customSection: "mt-4 pl-4 border-l border-amber-200",
        accentColor: "text-amber-700"
    },
    neon: {
        container: "bg-black p-8 max-w-2xl mx-auto border border-purple-500/20",
        name: "text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400",
        contact: "text-purple-300 text-xs tracking-widest mb-8",
        sectionTitle: "text-2xl font-bold text-pink-400 uppercase tracking-wider mb-4",
        itemTitle: "text-lg font-bold text-white",
        itemSubtitle: "text-sm text-purple-300",
        itemDescription: "text-gray-300 mt-2 text-sm",
        customSection: "mt-6 bg-gray-900/50 p-4 rounded-lg border border-purple-500/10",
        accentColor: "text-pink-400"
    },
    material: {
        container: "bg-white p-8 max-w-2xl mx-auto shadow-md rounded-lg",
        name: "text-4xl font-medium text-gray-800 mb-2",
        contact: "text-blue-600 text-sm mb-8",
        sectionTitle: "text-xl font-medium text-blue-700 bg-blue-50 px-3 py-2 rounded-lg mb-3",
        itemTitle: "text-lg font-medium text-gray-800",
        itemSubtitle: "text-sm text-blue-600",
        itemDescription: "text-gray-600 mt-1 text-sm",
        customSection: "mt-6 bg-gray-50 p-4 rounded-lg",
        accentColor: "text-blue-600"
    },
    glass: {
        container: "bg-white/10 backdrop-blur-md p-8 rounded-xl border border-white/20 shadow-lg",
        name: "text-4xl font-bold text-white",
        contact: "text-blue-100/80 text-sm mb-6",
        sectionTitle: "text-xl font-semibold text-white border-b border-white/20 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-white",
        itemSubtitle: "text-blue-100/70 text-sm",
        itemDescription: "text-white/80 text-sm mt-1"
    },
    brutalist: {
        container: "bg-yellow-100 p-6 border-4 border-black",
        name: "text-5xl font-black tracking-tight text-black mb-2",
        contact: "text-black/70 text-sm uppercase mb-8",
        sectionTitle: "text-2xl font-extrabold underline underline-offset-4 mb-4",
        itemTitle: "text-xl font-bold text-black",
        itemSubtitle: "text-black/60 text-sm font-mono",
        itemDescription: "text-black/80 text-sm mt-2 leading-tight"
    },
    cyberpunk: {
        container: "bg-black p-6 border-2 border-pink-500",
        name: "text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-500 to-blue-400",
        contact: "text-green-400 text-xs font-mono mb-8",
        sectionTitle: "text-xl font-bold text-pink-500 border-b border-pink-500/30 pb-1 mb-3",
        itemTitle: "text-lg font-bold text-white",
        itemSubtitle: "text-blue-400 text-xs font-mono",
        itemDescription: "text-gray-300 text-sm mt-1"
    },
    vintagePaper: {
        container: "bg-amber-50 p-8 border-l-8 border-amber-700 shadow-inner",
        name: "text-4xl font-serif text-amber-900 mb-2",
        contact: "text-amber-700/80 text-sm italic mb-8",
        sectionTitle: "text-xl font-serif text-amber-800 border-b border-amber-200 pb-1 mb-3",
        itemTitle: "text-lg font-serif text-amber-900",
        itemSubtitle: "text-amber-700/70 text-sm",
        itemDescription: "text-amber-800/80 text-sm mt-1 leading-relaxed"
    },
    biophilic: {
        container: "bg-white p-8 border-2 border-green-700/10 rounded-lg",
        name: "text-4xl font-bold text-green-800",
        contact: "text-green-600/80 text-sm mb-6",
        sectionTitle: "text-xl font-semibold text-green-700 border-b border-green-200 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-green-900",
        itemSubtitle: "text-green-600 text-sm",
        itemDescription: "text-green-800/80 text-sm mt-1"
    },
    minimalist: {
        container: "bg-white p-8 max-w-2xl mx-auto border border-gray-200",
        name: "text-3xl font-semibold text-gray-900 mb-3",
        contact: "text-sm text-gray-500 mb-6",
        sectionTitle: "text-lg font-medium text-gray-800 border-b border-gray-200 pb-2 mb-4",
        itemTitle: "text-base font-semibold text-gray-900",
        itemSubtitle: "text-sm text-gray-600",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6",
        accentColor: "text-gray-800"
    },
    retroTech: {
        container: "bg-teal-50 p-8 max-w-2xl mx-auto border-4 border-teal-700",
        name: "text-4xl font-mono text-teal-900 mb-2 tracking-tight",
        contact: "text-sm text-orange-600 font-mono mb-6",
        sectionTitle: "text-xl font-mono text-teal-800 border-b-2 border-orange-400 pb-2 mb-3",
        itemTitle: "text-lg font-mono text-teal-900",
        itemSubtitle: "text-sm text-orange-500 font-mono",
        itemDescription: "text-sm text-teal-800 mt-1",
        customSection: "mt-6 bg-teal-100/50 p-4 rounded",
        accentColor: "text-orange-600"
    },
    elegant: {
        container: "bg-gray-50 p-8 max-w-2xl mx-auto border-l-4 border-gold-600",
        name: "text-4xl font-serif text-gray-900 mb-2",
        contact: "text-sm text-gray-600 italic mb-6",
        sectionTitle: "text-xl font-serif text-gray-800 border-b border-gold-200 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-gray-900",
        itemSubtitle: "text-sm text-gold-600",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 pl-4 border-l-2 border-gold-200",
        accentColor: "text-gold-600"
    },
    futuristic: {
        container: "bg-gray-950 p-8 max-w-2xl mx-auto border border-cyan-500/30",
        name: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500",
        contact: "text-sm text-cyan-300 font-mono mb-6",
        sectionTitle: "text-xl font-bold text-cyan-400 border-b border-cyan-700/50 pb-2 mb-3",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-cyan-300 font-mono",
        itemDescription: "text-gray-300 text-sm mt-1",
        customSection: "mt-6 bg-gray-900/70 p-4 rounded-lg border border-cyan-500/10",
        accentColor: "text-cyan-400"
    },
    artDeco: {
        container: "bg-navy-50 p-8 max-w-2xl mx-auto border-t-8 border-navy-700",
        name: "text-4xl font-serif text-navy-900 mb-2 tracking-wide",
        contact: "text-sm text-navy-600 mb-6",
        sectionTitle: "text-xl font-serif text-navy-800 border-b-2 border-gold-400 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-navy-900",
        itemSubtitle: "text-sm text-gold-500 font-medium",
        itemDescription: "text-sm text-navy-700 mt-1",
        customSection: "mt-6 bg-navy-100/30 p-4 rounded",
        accentColor: "text-gold-500"
    },
    pastelDream: {
        container: "bg-white p-8 max-w-2xl mx-auto border border-pink-100 shadow-sm rounded-lg",
        name: "text-4xl font-semibold text-pink-600 mb-2",
        contact: "text-sm text-purple-500 mb-6",
        sectionTitle: "text-xl font-medium text-purple-600 border-b border-pink-200 pb-2 mb-3",
        itemTitle: "text-lg font-semibold text-gray-800",
        itemSubtitle: "text-sm text-pink-500",
        itemDescription: "text-sm text-gray-600 mt-1 leading-relaxed",
        customSection: "mt-6 bg-pink-50 p-4 rounded-md",
        accentColor: "text-purple-600"
    },
    monochromeBold: {
        container: "bg-white p-8 max-w-2xl mx-auto border-4 border-black",
        name: "text-4xl font-extrabold text-black mb-2 tracking-tight",
        contact: "text-sm text-gray-700 mb-6",
        sectionTitle: "text-xl font-bold text-black border-b-2 border-gray-900 pb-2 mb-3",
        itemTitle: "text-lg font-bold text-black",
        itemSubtitle: "text-sm text-gray-600 font-medium",
        itemDescription: "text-sm text-gray-800 mt-1",
        customSection: "mt-6 border-t-2 border-gray-900 pt-4",
        accentColor: "text-black"
    },
    oceanBreeze: {
        container: "bg-blue-50 p-8 max-w-2xl mx-auto border-l-4 border-teal-400",
        name: "text-4xl font-bold text-teal-700 mb-2",
        contact: "text-sm text-blue-600 mb-6",
        sectionTitle: "text-xl font-semibold text-teal-600 border-b border-blue-200 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-blue-500",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-blue-100/30 p-4 rounded",
        accentColor: "text-teal-600"
    },
    steampunk: {
        container: "bg-amber-100 p-8 max-w-2xl mx-auto border-2 border-bronze-600",
        name: "text-4xl font-serif text-bronze-800 mb-2 tracking-wide",
        contact: "text-sm text-amber-600 font-mono mb-6",
        sectionTitle: "text-xl font-serif text-bronze-700 border-b border-amber-300 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-bronze-800",
        itemSubtitle: "text-sm text-amber-500 font-mono",
        itemDescription: "text-sm text-amber-700 mt-1",
        customSection: "mt-6 bg-amber-200/50 p-4 rounded",
        accentColor: "text-bronze-600"
    },
    popArt: {
        container: "bg-white p-8 max-w-2xl mx-auto border-4 border-yellow-400",
        name: "text-4xl font-extrabold text-red-600 mb-2 tracking-tight",
        contact: "text-sm text-blue-600 uppercase mb-6",
        sectionTitle: "text-xl font-bold text-yellow-600 border-b-2 border-red-400 pb-2 mb-3",
        itemTitle: "text-lg font-bold text-black",
        itemSubtitle: "text-sm text-blue-500 font-bold",
        itemDescription: "text-sm text-gray-800 mt-1",
        customSection: "mt-6 bg-yellow-100 p-4 rounded-lg",
        accentColor: "text-red-600"
    },
    zenGarden: {
        container: "bg-gray-50 p-8 max-w-2xl mx-auto border border-green-200 rounded-lg",
        name: "text-4xl font-semibold text-green-800 mb-2",
        contact: "text-sm text-gray-600 mb-6",
        sectionTitle: "text-xl font-medium text-green-700 border-b border-green-100 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-green-600",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-green-50/50 p-4 rounded",
        accentColor: "text-green-700"
    },
    cosmicGlow: {
        container: "bg-black p-8 max-w-2xl mx-auto border border-indigo-500/30",
        name: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-violet-500",
        contact: "text-sm text-indigo-300 font-mono mb-6",
        sectionTitle: "text-xl font-bold text-violet-400 border-b border-indigo-700/50 pb-2 mb-3",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-indigo-300 font-mono",
        itemDescription: "text-gray-300 text-sm mt-1",
        customSection: "mt-6 bg-gray-900/80 p-4 rounded-lg border border-indigo-500/20",
        accentColor: "text-violet-400"
    },
    classicParchment: {
        container: "bg-amber-100 p-8 max-w-2xl mx-auto border-2 border-amber-600 shadow-inner",
        name: "text-4xl font-serif text-amber-900 mb-2 tracking-wide",
        contact: "text-sm text-amber-700 italic mb-6",
        sectionTitle: "text-xl font-serif text-amber-800 border-b border-amber-300 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-amber-900",
        itemSubtitle: "text-sm text-amber-600",
        itemDescription: "text-sm text-amber-800 mt-1 leading-relaxed",
        customSection: "mt-6 bg-amber-200/50 p-4 rounded",
        accentColor: "text-amber-700"
    },
    vibrantCitrus: {
        container: "bg-orange-50 p-8 max-w-2xl mx-auto border-l-4 border-lime-400",
        name: "text-4xl font-bold text-orange-600 mb-2",
        contact: "text-sm text-lime-600 mb-6",
        sectionTitle: "text-xl font-semibold text-orange-600 border-b border-lime-200 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-lime-500",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-lime-100/30 p-4 rounded",
        accentColor: "text-orange-600"
    },
    industrialForge: {
        container: "bg-gray-100 p-8 max-w-2xl mx-auto border-2 border-red-600",
        name: "text-4xl font-bold text-gray-800 mb-2 tracking-tight",
        contact: "text-sm text-red-600 font-mono mb-6",
        sectionTitle: "text-xl font-semibold text-gray-700 border-b border-red-300 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-red-500 font-mono",
        itemDescription: "text-sm text-gray-700 mt-1",
        customSection: "mt-6 bg-gray-200/50 p-4 rounded",
        accentColor: "text-red-600"
    },
    floralElegance: {
        container: "bg-cream-50 p-8 max-w-2xl mx-auto border border-pink-200 rounded-lg",
        name: "text-4xl font-serif text-pink-700 mb-2",
        contact: "text-sm text-pink-500 mb-6",
        sectionTitle: "text-xl font-medium text-pink-600 border-b border-pink-100 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-gray-800",
        itemSubtitle: "text-sm text-pink-500",
        itemDescription: "text-sm text-gray-600 mt-1 leading-relaxed",
        customSection: "mt-6 bg-pink-50/50 p-4 rounded",
        accentColor: "text-pink-600"
    },
    holoTech: {
        container: "bg-gray-900 p-8 max-w-2xl mx-auto border border-teal-500/20",
        name: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-purple-500",
        contact: "text-sm text-teal-300 font-mono mb-6",
        sectionTitle: "text-xl font-bold text-teal-400 border-b border-teal-700/50 pb-2 mb-3",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-teal-300 font-mono",
        itemDescription: "text-gray-300 text-sm mt-1",
        customSection: "mt-6 bg-gray-800/70 p-4 rounded-lg border border-teal-500/10",
        accentColor: "text-teal-400"
    },
    gothic: {
        container: "bg-gray-900 p-8 max-w-2xl mx-auto border-2 border-gray-700 shadow-lg",
        name: "text-4xl font-serif text-white mb-2 tracking-wide",
        contact: "text-sm text-gray-400 italic mb-6",
        sectionTitle: "text-xl font-serif text-gray-300 border-b border-gray-600 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-white",
        itemSubtitle: "text-sm text-gray-500 font-serif",
        itemDescription: "text-sm text-gray-400 mt-1 leading-relaxed",
        customSection: "mt-6 bg-gray-800 p-4 rounded border border-gray-700/50",
        accentColor: "text-gray-300"
    },
    retroArcade: {
        container: "bg-black p-8 max-w-2xl mx-auto border-4 border-red-500",
        name: "text-4xl font-mono text-blue-400 mb-2 tracking-tight",
        contact: "text-sm text-red-400 font-mono mb-6",
        sectionTitle: "text-xl font-mono text-blue-400 border-b-2 border-red-500 pb-2 mb-3",
        itemTitle: "text-lg font-mono text-white",
        itemSubtitle: "text-sm text-red-400 font-mono",
        itemDescription: "text-sm text-gray-300 mt-1",
        customSection: "mt-6 bg-gray-900 p-4 rounded border border-blue-500/20",
        accentColor: "text-blue-400"
    },
    midnightBloom: {
        container: "bg-blue-950 p-8 max-w-2xl mx-auto border-l-4 border-blue-400",
        name: "text-4xl font-serif text-blue-200 mb-2",
        contact: "text-sm text-blue-300 mb-6",
        sectionTitle: "text-xl font-serif text-blue-200 border-b border-blue-600 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-white",
        itemSubtitle: "text-sm text-blue-300",
        itemDescription: "text-sm text-gray-300 mt-1 leading-relaxed",
        customSection: "mt-6 bg-blue-900/50 p-4 rounded",
        accentColor: "text-blue-200"
    },
    tropicalVibe: {
        container: "bg-green-50 p-8 max-w-2xl mx-auto border border-yellow-300 rounded-lg",
        name: "text-4xl font-bold text-green-700 mb-2",
        contact: "text-sm text-yellow-600 mb-6",
        sectionTitle: "text-xl font-semibold text-green-600 border-b border-yellow-200 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-yellow-500",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-yellow-100/30 p-4 rounded",
        accentColor: "text-green-600"
    },
    baroqueOpulence: {
        container: "bg-cream-50 p-8 max-w-2xl mx-auto border-t-4 border-gold-600",
        name: "text-4xl font-serif text-gray-900 mb-2 tracking-wide",
        contact: "text-sm text-gold-600 italic mb-6",
        sectionTitle: "text-xl font-serif text-gray-800 border-b border-gold-300 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-gray-900",
        itemSubtitle: "text-sm text-gold-500",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-cream-100/50 p-4 rounded",
        accentColor: "text-gold-600"
    },
    neoMinimal: {
        container: "bg-white p-8 max-w-2xl mx-auto border border-gray-100",
        name: "text-3xl font-semibold text-gray-900 mb-3",
        contact: "text-sm text-gray-500 mb-6",
        sectionTitle: "text-lg font-medium text-indigo-600 border-b border-gray-200 pb-2 mb-3",
        itemTitle: "text-base font-semibold text-gray-900",
        itemSubtitle: "text-sm text-gray-600",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6",
        accentColor: "text-indigo-600"
    },
    purpleMajesty: {
        container: "bg-purple-50 p-8 max-w-2xl mx-auto border-l-4 border-purple-600 rounded-lg",
        name: "text-4xl font-bold text-purple-800 mb-2",
        contact: "text-sm text-purple-500 mb-6",
        sectionTitle: "text-xl font-semibold text-purple-700 border-b border-purple-200 pb-2 mb-3",
        itemTitle: "text-lg font-medium text-gray-900",
        itemSubtitle: "text-sm text-purple-600",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-purple-100/30 p-4 rounded",
        accentColor: "text-purple-700"
    },
    vintageTypewriter: {
        container: "bg-gray-100 p-8 max-w-2xl mx-auto border-2 border-gray-600",
        name: "text-4xl font-mono text-gray-800 mb-2 tracking-tight",
        contact: "text-sm text-gray-500 font-mono mb-6",
        sectionTitle: "text-xl font-mono text-gray-700 border-b border-gray-400 pb-2 mb-3",
        itemTitle: "text-lg font-mono text-gray-800",
        itemSubtitle: "text-sm text-gray-500 font-mono",
        itemDescription: "text-sm text-gray-600 mt-1 leading-relaxed",
        customSection: "mt-6 bg-gray-200/50 p-4 rounded",
        accentColor: "text-gray-700"
    },
    auroraGlow: {
        container: "bg-gray-900 p-8 max-w-2xl mx-auto border border-teal-500/30",
        name: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-purple-400",
        contact: "text-sm text-teal-300 mb-6",
        sectionTitle: "text-xl font-bold text-purple-400 border-b border-teal-600/50 pb-2 mb-3",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-teal-300",
        itemDescription: "text-sm text-gray-300 mt-1",
        customSection: "mt-6 bg-gray-800/70 p-4 rounded-lg border border-purple-500/20",
        accentColor: "text-purple-400"
    },
    artNouveau: {
        container: "bg-green-50 p-8 max-w-2xl mx-auto border-t-4 border-gold-500",
        name: "text-4xl font-serif text-green-800 mb-2 tracking-wide",
        contact: "text-sm text-gold-600 mb-6",
        sectionTitle: "text-xl font-serif text-green-700 border-b border-gold-200 pb-2 mb-3",
        itemTitle: "text-lg font-serif text-green-800",
        itemSubtitle: "text-sm text-gold-500",
        itemDescription: "text-sm text-gray-700 mt-1 leading-relaxed",
        customSection: "mt-6 bg-green-100/30 p-4 rounded",
        accentColor: "text-green-700"
    },
    cyberGrid: {
        container: "bg-black p-8 max-w-2xl mx-auto border-2 border-green-500/50",
        name: "text-4xl font-mono text-green-400 mb-2 tracking-tight",
        contact: "text-sm text-blue-400 font-mono mb-6",
        sectionTitle: "text-xl font-mono text-green-400 border-b border-blue-500/50 pb-2 mb-3",
        itemTitle: "text-lg font-mono text-white",
        itemSubtitle: "text-sm text-blue-400 font-mono",
        itemDescription: "text-sm text-gray-300 mt-1",
        customSection: "mt-6 bg-gray-900/80 p-4 rounded border border-green-500/20",
        accentColor: "text-green-400"
    },
    gradientPulse: {
        container: "bg-gradient-to-br from-purple-600 to-teal-500 p-8 max-w-2xl mx-auto rounded-xl shadow-lg hover:shadow-xl transition-shadow duration-300 border border-purple-400/50",
        name: "text-4xl font-extrabold text-white mb-2 tracking-wide",
        contact: "text-sm text-teal-200 mb-6",
        sectionTitle: "text-xl font-bold text-white border-b border-teal-400/50 pb-2 mb-3 hover:scale-105 transition-transform duration-200",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-teal-300",
        itemDescription: "text-sm text-gray-200 mt-1 leading-relaxed",
        customSection: "mt-6 bg-white/10 backdrop-blur-sm p-4 rounded-lg border border-teal-400/30",
        accentColor: "text-teal-400"
    },
    cosmicWave: {
        container: "bg-gradient-to-r from-blue-900 to-pink-800 p-8 max-w-2xl mx-auto rounded-lg shadow-md backdrop-blur-sm border border-pink-400/30",
        name: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-blue-400 mb-2",
        contact: "text-sm text-pink-300 mb-6",
        sectionTitle: "text-xl font-bold text-white border-b border-pink-400/50 pb-2 mb-3",
        itemTitle: "text-lg font-semibold text-white hover:text-pink-200 transition-colors duration-200",
        itemSubtitle: "text-sm text-pink-300",
        itemDescription: "text-sm text-gray-200 mt-1",
        customSection: "mt-6 bg-pink-900/20 backdrop-blur-md p-4 rounded-lg shadow-sm",
        accentColor: "text-pink-400"
    },
    neonHorizon: {
        container: "bg-gradient-to-t from-orange-600 to-cyan-600 p-8 max-w-2xl mx-auto rounded-xl border-2 border-cyan-400 shadow-lg hover:shadow-cyan-400/50 transition-shadow duration-300",
        name: "text-4xl font-extrabold text-white mb-2 tracking-tight",
        contact: "text-sm text-cyan-300 font-mono mb-6",
        sectionTitle: "text-xl font-mono text-cyan-300 border-b border-orange-400/50 pb-2 mb-3 hover:scale-105 transition-transform duration-200",
        itemTitle: "text-lg font-mono text-white",
        itemSubtitle: "text-sm text-orange-300 font-mono",
        itemDescription: "text-sm text-gray-200 mt-1",
        customSection: "mt-6 bg-cyan-900/30 p-4 rounded-lg border border-orange-400/20",
        accentColor: "text-cyan-300"
    },
    twilightSpark: {
        container: "bg-gradient-to-br from-indigo-900 to-violet-700 p-8 max-w-2xl mx-auto rounded-lg shadow-lg border border-violet-400/40",
        name: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-violet-400 to-indigo-400 mb-2",
        contact: "text-sm text-violet-300 mb-6",
        sectionTitle: "text-xl font-bold text-violet-200 border-b border-indigo-400/50 pb-2 mb-3 relative after:content-[''] after:absolute after:bottom-0 after:left-0 after:h-[2px] after:bg-gradient-to-r after:from-violet-400 after:to-indigo-400 after:w-0 after:transition-all after:duration-300 hover:after:w-full",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-indigo-300",
        itemDescription: "text-sm text-gray-200 mt-1",
        customSection: "mt-6 bg-violet-900/20 p-4 rounded-lg border border-indigo-400/30",
        accentColor: "text-violet-400"
    },
    solarFlare: {
        container: "bg-gradient-to-r from-red-600 to-yellow-500 p-8 max-w-2xl mx-auto rounded-xl shadow-lg hover:shadow-yellow-400/50 transition-shadow duration-300 border border-yellow-400/40",
        name: "text-4xl font-extrabold text-white mb-2 tracking-wide",
        contact: "text-sm text-yellow-300 mb-6",
        sectionTitle: "text-xl font-bold text-white border-b border-yellow-400/50 pb-2 mb-3 hover:text-yellow-200 transition-colors duration-200",
        itemTitle: "text-lg font-semibold text-white",
        itemSubtitle: "text-sm text-red-300",
        itemDescription: "text-sm text-gray-200 mt-1",
        customSection: "mt-6 bg-yellow-900/20 backdrop-blur-sm p-4 rounded-lg border border-red-400/30",
        accentColor: "text-yellow-400"
    }
}